[proxmox]
proxmox ansible_host=10.0.0.2 ansible_user=root

[vms]
debiandelmundo ansible_host=10.0.0.10 ansible_user=root
vaultwardenvm ansible_host=10.10.10.2 ansible_user=root
monitorvm ansible_host=10.0.0.3 ansible_user=ansible

[external]
oracle-vps ansible_host=129.80.162.234 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/jarebare/Documents/Keys/ssh-key-2025-05-23.key ansible_python_interpreter=/usr/local/bin/python3.10

[all:vars]
ansible_python_interpreter=/usr/bin/python3
